### PR TITLE
Cross-build for ScalaJS and Scala Native.

### PR DESCRIPTION
**Pull request by arturaz**
Resurrection of https://github.com/jkugiya/ulid-scala/pull/9

Now it should work, I ran `++ test` (tests on all platforms) on my machine.

I had to:
- resort to simple Random on JS/native platforms, as SecureRandom is only available on JVM.
- shuffle some code around to allow that.
- drop Scala 2.11 support, as js & native do not support it as well.

### CODE REVIEW

**Comment by arturaz** [comment]
Anything else I can do to get this merged?

**Comment by arturaz** [comment]
Hey @jkugiya - if you are not interested in maintaining this package, could I take over as a maintainer?

**Comment by jkugiya** [comment]
@arturaz

Sorry, It seems that the notification was classified as spam and I didn't notice it.
It's nighttime in my time zone now, so I'll check it tomorrow morning and release it if there are no problems.

**Review by jkugiya — APPROVED** [review]
LGTM

**Comment by arturaz** [comment]
Will you release a new version? :)

**Comment by jkugiya** [comment]
1.05 is available
https://mvnrepository.com/artifact/com.github.jkugiya/ulid-scala_3/1.0.5

**Pull request merged**
