### PR TITLE
Cross-build for ScalaJS and Scala Native.

### PR DESCRIPTION
**Pull request by arturaz**

### CODE REVIEW

**Comment by jkugiya** [comment]
nice!

**Comment by jkugiya** [comment]
@arturaz Sorry, I have reverted this one becase CI failed.
https://github.com/jkugiya/ulid-scala/actions/runs/10554198422/job/29235650764

**Comment by arturaz** [comment]
> @arturaz Sorry, I have reverted this one becase CI failed. https://github.com/jkugiya/ulid-scala/actions/runs/10554198422/job/29235650764

This should fix it: https://github.com/jkugiya/ulid-scala/commit/2090a03196ddba0455f862e3ef255cc1ba10901d

**Comment by jkugiya** [comment]
Still it failed.

https://github.com/jkugiya/ulid-scala/pull/12

Current matrix:
https://github.com/jkugiya/ulid-scala/blob/main/.github/workflows/ci.yml#L10-L11

**Pull request merged**
